import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import PlayerProvider from "./context/PlayerContext";
import PlayerOverlay from "./components/player/PlayerOverlay";
import ServerListProvider from "./context/ServersContext";
import Topbar from "./components/Topbar";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PlayerProvider>
        <ServerListProvider>
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative w-screen h-[100dvh] overflow-hidden flex justify-center`}>
            <Toaster theme="dark" />
            <PlayerOverlay />
            <Navbar />
            <div className="md:ml-[62px] gap-4 grid grow grid-rows-[auto_1fr] p-4 max-w-[2000px]">
              <Topbar />
              <main className="relative overflow-auto p-3">
                {children}
              </main>
            </div>
          </body>
        </ServerListProvider>
      </PlayerProvider>
    </html>
  );
}
